name: BUILD

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - run: git fetch --prune --unshallow
    - run: git fetch --tags

    - run: yarn install
    - run: yarn add --dev alfa-ui-primitives@latest
    - run: yarn generate

    - name: Commit files
      run: |
        git config --local user.email "ds@alfabank.ru"
        git config --local user.name "alfa-bot"
        git commit -m "feat(*): add new icons" -a
    
    - name: lerna up version
      uses: "MrBoolean/action-lerna@master"
      with:
       args: version minor --no-push --yes

    - run: yarn build

    - name: Set NPM Token Action
      uses: filipstefansson/set-npm-token-action@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    
    - run: npm set registry https://registry.npmjs.org

    - name: Commit files
      run: |
        git commit -m "feat(*): add gen files" -a

    - run: yarn generate-json
      env:
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

    - run: yarn publish-root-package
    
    - name: Commit files
      run: |
        git commit -m "feat(*): add gen files" -a

    - name: lerna publish subpackages
      uses: "MrBoolean/action-lerna@master"
      with:
        args: publish from-git --contents dist --yes

    - name: Commit files
      run: |
          git commit -m "feat(*): add gen files" -a
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOT_AUTH_TOKEN }}
        tags: true

    - run: curl -X POST -u '${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}' -H 'Accept:\ application/vnd.github.everest-preview+json' -H 'Content-Type:\ application/json' https://api.github.com/repos/alfa-laboratory/icons-demo/dispatches --data '{"event_type":"build_application"}'
